### ISSUE TITLE
Webpack compilation error - Class private methods are not enabled

### ISSUE THREAD

**Issue by clazette** [cypress-io/github-action#402]
I have some classes utilizing private methods. Cypress 7.6.0 didn't have an issue. When I upgraded to 7.7.0, this Webpack compilation error began occurring. Is there a way around this?

Error: Webpack Compilation Error
Module build failed (from C:/Users/UserDir/AppData/Local/Cypress/Cache/7.7.0/Cypress/resources/app/packages/server/node_modules/babel-loader/lib/index.js):
SyntaxError: Class private methods are not enabled.

**Comment by MikeMcC399** [comment]
This is a stale issue and it describes an issue with a legacy version of Cypress, not with `github-action`.
